# LoadBalancer Service. Will only work on supported cloud platforms (AKS, EKS, GKE, DOK, IBM, LKE etc...)
# Listens externally on 3000 and forwards to Pod/container on 45231
apiVersion: v1
kind: Service
metadata:
  name: lb-portfolio-website
spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 45231
  selector:
    app: web