apiVersion: v1
kind: Service
metadata:
  name: np-portfolio-website
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 45231
      nodePort: 31111
